// <auto-generated />
namespace Patholabs_Express.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class User_AdminDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_AdminDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202106111743558_User_AdminDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
