// <auto-generated />
namespace Patholabs_Express.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class appointment_DetailsDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appointment_DetailsDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202106161317315_appointment_DetailsDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
